apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: "meubanco"
  POSTGRES_USER: "admin"
  POSTGRES_HOST: "localhost"
  MAX_CONNECTIONS: "100"
  TIMEZONE: "America/Sao_Paulo"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_PASSWORD: bWluaGFzZW5oYTEyMw== ## needs to bee base 64


--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        envFrom:
          - configMapRef:
              name: postgres-config ## inject var as env on pod
          - secretRef:
              name: postgres-secret
